@startuml

class AAUOC {
    newLocation(l : Location) : void
    newEvent(e : Event) : void
    newPerson(p : Person) : void
    informEvent(e : Event) : void
    register(m : Member,e : Event) : void
}

class Location {
    description : String
    address : String
}

class Event {
    date : Date
    description : String
    assign(l : Location) : void
}

class Conference {
    max_attendees : Integer
}

class BoardMeeting {

}

class Person {
    name : String
}

class Member {
    e-mail : String
}

class BoardMember {

}

AAUOC o-down- "0..*" Location

AAUOC o-down- "0..*" Event

AAUOC o-left- "0..*" Person

Location "1" - "0..*" Event : isLocatedIn

Person "0..*" -- "0..*" Conference : attendsTo

Event <|-- Conference

Event <|-- BoardMeeting

Person <|-down- Member

Member <|-down- BoardMember

Member "0..*" - "0..*" Event : attendsTo

BoardMember "0..*" - "0..*" BoardMeeting : attendsTo

@enduml